### ISSUE TITLE
LayeredWorld.gd has unreliable planet retention and spawning issues

### ISSUE THREAD

**Issue by Vine2D** [GDQuest/godot-procedural-generation#1]
**I'm submitting a...**

- [x] Bug report.
- [ ] Feature request.

## Bug report ##

**What is the current behavior?**
\SpaceInfiniteGeneration\03-LayeredGeneration\LayeredWorld.gd
If you fly far away enough from a planet for it to queue_free() then fly back towards it to reload it, the code will begin to spawn hundreds of instances of that planet over time. This behavior also causes unreliability when planets are loaded. Sometimes they fail to appear at all if attempted to reload them.

**What is the expected behavior?**
Planets load/unload reliably, and without creating additional nodes every frame.

**Tell us the steps to reproduce the bug, and if possible share a minimal demo of the problem.** 
1. Run LayeredWorld.tscn
2. Travel away from any planet on-screen until it unloads
3. Travel back towards that planet until it should reload
4. Observe the remote tree as it is populated with planets over time

**Comment by NathanLovato** [comment]
I think it's a work-in-progress, @Razoric480 pushed this today. But thanks for the report!

**Comment by Razoric480** [comment]
That's... an unusual bug, and I'm unable to recreate it. There isn't any code that causes the generation to happen per-frame, only when you move beyond a certain threshold.

That said, I'm not too satisfied with the code as is so I'm revisiting it anyway; we'll see if the issue persists then.

**Comment by Razoric480** [comment]
I've pushed a new and better generation algorithm, so it shouldn't happen anymore.

**Comment by NathanLovato** [comment]
Closing for now, we'll reopen if the bug happens again with the new code.
