### ISSUE TITLE
Port to Godot 4.0

### ISSUE THREAD

**Issue by Omiod** [GDQuest/godot-procedural-generation#10]
**I'm submitting a...**

- [ ] Bug report.
- [x] Feature request.

**Comment by NathanLovato** [comment]
Good news for you! Contributor @tlobig has been porting this project to Godot 4: https://github.com/tlobig/godot-procedural-generation/tree/godot4update

I haven't had the time to review this yet but Godot 4 support is in the works

**Comment by tlobig** [comment]
thanks for the mention @NathanLovato 
I'm close to done with the first pass, only the last to parts of the course are not yet ported.
The code has a lot of comments to help with review, but should go before a merge.
Finally the new capabilities of Godot 4 enable a few ways to better structure the code and I will not have fully leveraged this on the first pass.

**Comment by NathanLovato** [comment]
Don't hesitate to open a pull request once you'd like a review. We can directly refactor on top of your work + share insights on the changes if you're comfortable with that, which is the most efficient review option, or we can provide comments for you to make changes yourself if you prefer.

**Comment by Omiod** [comment]
Awesome! Thank you very much!

**Comment by tlobig** [comment]
Let's go ahead an change it together. I'd love some constructive feedback. I expect to be done with infinite worlds and cellular automota in the next few days. The course text will also need to be updated eventually.

**Comment by tlobig** [comment]
I touched everything in the godot folder and have even started on a second pass through, tidying up some things in the basic dungeon and random walker parts. I will now await further direction before cleaning up the rest. Meanwhile all demos are in a usable state with Godot 4.0 stable

**Comment by Omiod** [comment]
Awesome! Most of them works!
But some like the MSTDungeon and RandomWalker have the error "Parser Error: Unable to iterate on object of type "Node"."

**Comment by tlobig** [comment]
Thank you for testing. Try RandomWalker again, I think the error you mention is only in MSTDungeon and it looks like a new issue that came with the stable 4.0 release.

**Comment by tlobig** [comment]
I pushed an update for MSTDungeon, it still crashes if I remove the print statement print("_add_rooms") which is super weird. Could be anything. So, it works now, but this lurking bug needs to be squashed.

**Comment by Omiod** [comment]
Thank you! RandomWalker works fine.
That bug is quite weird indeed.

**Comment by NathanLovato** [comment]
@tlobig thank you so much! I really want to give you a proper review quickly but I'm still overloaded with work with GDC next week. I'll ask the teammate who put the most work on this project if he can handle that. He works at GDQuest Thursday to Saturday.

**Comment by tlobig** [comment]
@NathanLovato please don't stress yourself out about this review. You obviously have to have your mind on GDC now. All in good time. I just wish I had more time to spend on things like these - is all I'll allow myself to publicly state.

**Comment by jipiboily** [comment]
Any news on review and the update to the course by any chance? :)

**Comment by tlobig** [comment]
it's done for months, the issue should be closedAm 07.10.2023 01:31 schrieb JP Boily ***@***.***>:
Any news on review and the update to the course by any chance? :)

**Comment by NathanLovato** [comment]
Thanks for the reminder to close! @jipiboily see the folder godot4/ that contains the Godot 4 port of the demos
