### ISSUE TITLE
Writing generation data to a file !!!

### ISSUE THREAD

**Issue by gxhamster** [GDQuest/godot-procedural-generation#2]
This decrease the amount of processing each time

**Comment by NathanLovato** [comment]
What's the issue about? Is it a request?

If you'd like to write a generated procedural world's data to a file, you already can. But that would be beyond the scope of showing and teaching PCG algorithms, which is what this demo is about.

**Comment by NathanLovato** [comment]
I'll close the issue for now as it doesn't seem relevant to this repository. If you can give us more detail on what you mean and how it's relevant to this project, it's welcome and we can reopen the issue.
