### ISSUE TITLE
Add cellular automata demos

### ISSUE THREAD

**Issue by cogwoz** [GDQuest/godot-procedural-generation#4]
# Demos for the cellular automata chapter

A new chapter in the procedural generation course will have four accompanying demo scenes teaching the basics of cellular automata. Each demo focuses on a new feature to eventually create a pleasing randomized dungeon the user can move around in with doodads such as doors and chests.

## Demo 1 - Creating Simple Foliage

This introduces the idea of cellular automata using a modified version of Conway's Game of Life to generate patches of foliage. The idea is to show how users could quickly generate randomized content for their game.

## Demo 2 - Basic Dungeon Generation

Here we create an empty dungeon with sliders to control the generation's look and feel. Moving the sliders instantly updates the dungeon.

## Demo 3 - Increasing the Dungeon's Appeal

This demo shows how to make the dungeon look good using a tilemap and tile variations.

## Demo 4 - The Final Dungeon

In the final demo, we show how to handle gameplay using what we learnt. We place an entrance, exit, doors and chests to create simple, playable level.

**Comment by NathanLovato** [comment]
The demos 2 to 4 are the same project, but at 3 different stages of completion, right?

Looking good.

**Comment by cogwoz** [comment]
Pretty much! I'll try and make it so after each step there is something the user can branch off of if they want.
