### ISSUE TITLE
numerous examples do not work

### ISSUE THREAD

**Issue by pracplayopen** [GDQuest/godot-procedural-generation#7]
**I'm submitting a...**

- [X ] Bug report.
- [ ] Feature request.

## Bug report ##

**What is the current behavior?**

from the docs at: https://github.com/GDQuest/godot-procedural-generation#how-to-use

```
How to use
Clone the repository. Each demo is in a separate directory.
```
Cloning works, opening project file works.   

There are 5 demos (one with 3 sub-demos, aka 'cellular automota' or CA for abbrev).  

Of the 5 demos:

* 3 of 5 have both main scene and code (CA, ModularWeapons and SpaceInfinite)
* 2 of 5 have only assets but no code nor scene file (WorldMap and RandomWalker), and thus can't be run at all
* of the 3/5 demos with scene and code (or 6/8 if you count 3 sub-demos inside CA) only 1 scene does anything like what the docs say they should  (CA.dungeongenerator, the other two CA modules show a UI control but don't respond to pressing it).   
* The other non-CA modules display an asset on screne, but have no controls and don't appear to do anything.

**What is the expected behavior?**

For a demo project, would generally expect to be able to download and run it to see behavior described in docs.

**Tell us the steps to reproduce the bug, and if possible share a minimal demo of the problem.** 

1. clone the project as described on project README file (and repeated above in this issue)
2. open project file in godot
3. locate the folder for demo you wish to run (eg Modular Weapons)
4. locate scene file 'tscn' in this folder, right click this file and choose 'set to main scene'
5. start demo clicking godot's 'play' button
6. expect: see behavior described in docs instead: we see static assets that don't respond (w/exception of CA.Dungeons, which works as described)

## Feature request ##

n/a

## Other ##

**Other information** 

* tested using godot-3.3.3.stable.mono.official [b973f997f]

**Comment by NathanLovato** [comment]
Did you open the start-project folder instead of the final godot/ project? The start-project is for our course, Godot PCG Secrets, it's a starting point for the tutorials.

All demos work here. Please ensure you imported the godot/ directory.

**Comment by pracplayopen** [comment]
thx for response.

we're not taking any course, just found your project via google and noticed README instructions did not yield a successful result.

simply followed repo's current README.md (as of around 10:30p EST on 11/8/2021, few hours ago as of this post)

$ git describe --tags
1.0.0-40-g71a3b0b

two suggested solutions:

1. update readme to link to whatever course you're referencing
2. update readme to include instructions different what is there presently.

see above if you want to see how to reproduce a situation where a random walk into your project builds fine but doesn't work for most of projects.

was pretty big discrepency so usually worth sharing.   seems like you don't care so will close.

best

**Comment by NathanLovato** [comment]
> seems like you don't care so will close.

Please don't assume that and don't treat content creators like that. I did take the time to reply to you; you could've made a little PR to change that.

I'll add a line to the README to specify that right away.
