### ISSUE TITLE
Potentially misnamed var `_total_sector_count` & suggestion

### ISSUE THREAD

**Issue by benhorst** [GDQuest/godot-procedural-generation#8]
**I'm submitting a...**

- [ ] Bug report.
- [x] Feature request.

## Feature request ##
I'll call this a feature request, as I haven't read all the code and don't feel comfortable submitting a PR at this time. Excellent examples! This has helped me get up to speed on GDscript as well as Godot. First off, thank you!

I got hung up on learning how the WorldGenerator works given a bit of perceived inconsistency in variable names (because frankly, a lot of the variable names are quite descriptive and I understood most of them right away). This specific section of code confused me in context:

```
## Total number of sectors to generate around the player.
onready var _total_sector_count := sector_size * sector_size
```
Given `sector_size = 1000` (in world coordinate units) and the sector axis count is more like 10 (overridden to 16 in the example, in units of sectors), the "sector count" computes to `10_000`. The count of sectors, however, is 100 (or 256 in the actual scene with export/tool overrides).

Then later, in the physics process, it is used to find which sector the player is in:
```
var sector_location := _current_sector * sector_size
if _player.global_position.distance_squared_to(sector_location) > _total_sector_count:
```

In this case (I'm not sure if there are others), the `_total_sector_count` is being used more like a pre-computed size for the Sector length to use with _distance_squared_to. The unit of the "total sector count" is actually in world coordinates, not sector counts. I expected it to be the square of `_sector_axis_count` based on its name.

**Tell us which solutions you've explored, the solution you would pick, and why you think it would be the best for everyone.**

It may be appropriate to rename the variable `_total_sector_count` to `_sector_size_squared` with an adjusted comment for what it represents. This comment "Total number of sectors to generate around the player" appears to be wholly independent of the variable's value at this time.

I have probably over-explained myself, but I hope this finds you well :)

**Comment by benhorst** [comment]
One small addition to this is that the very next variable _does_ actually represent a "sector count" and it is closely associated but is based on different units

```
## Total number of sectors to generate around the player.
onready var _total_sector_count := sector_size * sector_size
## And this is half of `_total_sector_count`.
onready var _half_sector_count := int(sector_axis_count / 2.0)
```

I have to imagine this is an artifact of a refactor at some point. I don't mean to harp on it :)

**Comment by NathanLovato** [comment]
Yes absolutely it's incorrect, we should fix it.

**Comment by benhorst** [comment]
cheers, have a good one!

And thanks again for maintaining good examples. I've got a lot more stuff working today than I did yesterday 🙏 . I appreciate the contributors.
